name: Publish server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cargo toolchain
        uses: actions-rs/toolchain@v1
        with:
          target: aarch64-unknown-linux-gnu
          override: true

      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: >
            --target aarch64-unknown-linux-gnu
            --bin veloren-server-cli
            --release
            --no-default-features
            --features default-publish

      - name: Copy build output
        run: cp target/aarch64-unknown-linux-gnu/release/veloren-server-cli ./veloren-server-cli

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_PAT }}

      - name: Build docker image and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./server-cli/Dockerfile
          platforms: linux/arm64
          push: true
          tags: ghcr.io/shoyuvanilla/veloren-server-cli:latest
